### ISSUE TITLE
Backport to 1.20.1

### ISSUE THREAD

**Issue by aleksandarbst** [Tomate0613/birds-boids#2]
Could this pretty please be backported to version 1.20.1? Pretty please with berries and cherries on top? 
This is the only implementation of birds I have found and it's gorgeous.

In all fairness this isn't vital at all and once other mods catch up to 1.20.4 then it won't be an issue. Feel free to close this request

**Comment by Tomate0613** [comment]
Here you go: https://modrinth.com/mod/birds-boids-addon/version/JK2QzDCr
