### ISSUE TITLE
Birds flying on the ground!

### ISSUE THREAD

**Issue by FoxFlummox** [Tomate0613/birds-boids#5]
The birds seem to fly along the ground like they are land animals. Is there a way to fix this?

**Comment by PieceMaker085** [comment]
Yeah, as of 1.1.0 it seems to be the case. Birds are not up in the air any longer but flying near that ground without changing altitude.

**Comment by benruehl** [comment]
The bird flying height seems to be fixed at 100 to 120 ([see here](https://github.com/Tomate0613/birds-boids/blob/4bf3053c72ca07b007fb95a6f368617badd89d77/src/main/java/dev/doublekekse/birdsboids/entities/bird/Bird.java#L36)). When using terrain generators like Terralith / Tectonic or similar this height can easily be way too low. One world I tested has valleys at around 160 and mountain tops at 250 or higher. My guess is that this is the reason the birds spawn on the ground in these areas.

**Comment by PieceMaker085** [comment]
I don't use any terrain generation mods or anything that alters the world height though.

I will try and make a better analyzation at some point.

**Comment by Fyoncle** [comment]
@Tomate0613 Any news on that? I also experience this

**Comment by RKDeviancy** [comment]
+1 just to confirm that this is still happening on the most up-to-date 1.21.1 file (1.3.0)

**Comment by Fyoncle** [comment]
> Would be great if someone could confirm if this actually works, but it should be fixed now https://github.com/Tomate0613/birds-boids/actions/runs/12214594107

![image](https://github.com/user-attachments/assets/ab04d242-ef20-47d2-a071-6d20007d87f5)
Confirmed they do work.
